# Generated by Django 4.0 on 2022-01-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoping_app', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalprice',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
